apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud?ref=controller-v1.8.2
patchesStrategicMerge:
- patches.yaml
