repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-rollouts
  namespace: argo-rollouts
  chart: argo/argo-rollouts
  version: 2.40.3
  values:
  - values.yaml
