apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: trace-collector
spec:
  mode: "deployment"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors: {}

    exporters:
      debug: {}
      otlp:
        endpoint: tempo-grafana-distributor.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlp]