# see: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubernetes-without-kube-proxy
kubeProxyReplacement: true
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
# ensure pods roll when configmap updates
rollOutCiliumPods: true
# see: https://docs.cilium.io/en/latest/observability/visibility/#layer-7-protocol-visibility
endpointStatus:
  enabled: true
  status: policy
gatewayAPI:
  enabled: true
ingressController:
  enabled: true
  # default is ingress-nginx
  default: false
  enforceHttps: false
  loadbalancerMode: shared
  service:
    type: NodePort
    insecureNodePort: 31080
    secureNodePort: 31443
operator:
  # ensure pods roll when configmap updates
  rollOutPods: true
  prometheus:
    enabled: true
prometheus:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    # Visualization of l7 protocols
    podAnnotations:
      policy.cilium.io/proxy-visibility: "<Ingress/8081/TCP/HTTP>"
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
