apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-image-pull
  namespace: troubleshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-image-pull
  template:
    metadata:
      labels:
        app: app-image-pull
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.25.0
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: app-image-pull
  namespace: troubleshoot
spec:
  selector:
    app: app-image-pull
  ports:
  - port: 80
    targetPort: 8080
