repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: loki
  namespace: monitoring
  createNamespace: true
  chart: grafana/loki
  version: 6.16.0
  values:
  - loki-values.yaml
