repositories:
- name: cilium
  url: https://helm.cilium.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: cilium
  namespace: kube-system
  chart: cilium/cilium
  version: 1.18.6
  values:
  - values/cilium.values.yaml
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.13.1
  values:
  - values/ingress-nginx.values.yaml
