repositories:
  - name: istio-official
    url:  https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    chart: istio-official/base
    version: 1.19.0

  - name: istio-misc
    namespace: istio-system
    chart: ../charts/istio-misc
    disableValidation: true
    needs:
      - /istio-base

  - name: istiod
    namespace: istio-system
    chart: istio-official/istiod
    version: 1.19.0
    wait: true
    values:
      - ../values/istiod.values.yaml

  - name: istio-ingressgateway
    namespace: istio-system
    chart: istio-official/gateway
    version: 1.19.0
    needs:
      - istio-system/istiod
    values:
      - ../values/ingressgateway.values.yaml
