apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-by-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: app.argocd.vm02.handson.cloudnativedays.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: handson
            port:
              name: http
