repositories:
- name: headlamp
  url: https://kubernetes-sigs.github.io/headlamp/

releases:
- name: headlamp
  namespace: headlamp
  chart: headlamp/headlamp
  version: 0.39.0
  values:
  - values.yaml
